import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const definitionPath = resolve(repositoryRoot, "isa/v1.json");
const checkOnly = process.argv.slice(2).includes("--check");

function invariant(condition, message) {
  if (!condition) throw new Error(`Invalid ISA definition: ${message}`);
}

function isIntegerInRange(value, maximum) {
  return Number.isInteger(value) && value >= 0 && value <= maximum;
}

function assertUnique(items, property, label) {
  const seen = new Set();
  for (const item of items) {
    invariant(!seen.has(item[property]), `duplicate ${label} ${item[property]}`);
    seen.add(item[property]);
  }
}

function validateDefinition(definition) {
  invariant(definition.name === "jimp-portable-vm", "unexpected ISA name");
  invariant(isIntegerInRange(definition.formatVersion?.major, 0xffff), "invalid major version");
  invariant(isIntegerInRange(definition.formatVersion?.minor, 0xffff), "invalid minor version");
  invariant(definition.endianness === "little", "only little-endian is supported");
  invariant(definition.opcodeWidth === 1, "v1 opcodes must occupy one byte");
  invariant(definition.reservedValues?.noRegister === 0xffff, "NO_REGISTER must be 0xffff");
  invariant(Array.isArray(definition.operandTypes), "operandTypes must be an array");
  invariant(Array.isArray(definition.valueTypes), "valueTypes must be an array");
  invariant(Array.isArray(definition.instructions), "instructions must be an array");

  assertUnique(definition.operandTypes, "name", "operand type");
  assertUnique(definition.valueTypes, "name", "value type name");
  assertUnique(definition.valueTypes, "tag", "value type tag");
  assertUnique(definition.instructions, "name", "instruction name");
  assertUnique(definition.instructions, "opcode", "opcode");

  const operandTypes = new Set(definition.operandTypes.map(({ name }) => name));
  for (const operandType of definition.operandTypes) {
    invariant(/^[a-z][a-z0-9_]*$/.test(operandType.name), `invalid operand type ${operandType.name}`);
    invariant(["u16", "u32"].includes(operandType.encoding), `invalid encoding for ${operandType.name}`);
    invariant(typeof operandType.allowsNoRegister === "boolean", `invalid NO_REGISTER rule for ${operandType.name}`);
    invariant(!operandType.allowsNoRegister || operandType.encoding === "u16", `${operandType.name} cannot encode NO_REGISTER`);
  }

  for (const valueType of definition.valueTypes) {
    invariant(/^[A-Z][A-Z0-9_]*$/.test(valueType.name), `invalid value type ${valueType.name}`);
    invariant(isIntegerInRange(valueType.tag, 0xff), `invalid tag for ${valueType.name}`);
    invariant(typeof valueType.runtimeValue === "boolean", `invalid runtimeValue for ${valueType.name}`);
    invariant(valueType.description?.en && valueType.description?.pt, `missing descriptions for ${valueType.name}`);
  }

  for (const instruction of definition.instructions) {
    invariant(/^[A-Z][A-Z0-9_]*$/.test(instruction.name), `invalid instruction ${instruction.name}`);
    invariant(isIntegerInRange(instruction.opcode, 0xff), `invalid opcode for ${instruction.name}`);
    invariant(Array.isArray(instruction.operands), `missing operands for ${instruction.name}`);
    invariant(instruction.description?.en && instruction.description?.pt, `missing descriptions for ${instruction.name}`);
    assertUnique(instruction.operands, "name", `operand in ${instruction.name}`);
    for (const operand of instruction.operands) {
      invariant(/^[a-z][a-z0-9_]*$/.test(operand.name), `invalid operand ${instruction.name}.${operand.name}`);
      invariant(operandTypes.has(operand.type), `unknown operand type ${operand.type}`);
    }
  }

  for (const requiredType of ["NULL", "BOOL", "I64", "F64", "STRING", "VOID"]) {
    invariant(definition.valueTypes.some(({ name }) => name === requiredType), `missing ${requiredType} value type`);
  }
  for (const requiredInstruction of [
    "LOAD_CONST", "MOVE", "HOST_CALL",
    "NEGATE", "ADD", "SUBTRACT", "MULTIPLY", "DIVIDE", "REMAINDER",
    "EQUAL", "NOT_EQUAL", "LESS_THAN", "LESS_EQUAL", "GREATER_THAN", "GREATER_EQUAL",
    "BOOL_NOT", "BOOL_AND", "BOOL_OR",
    "JUMP", "JUMP_IF_FALSE", "JUMP_IF_TRUE", "CALL", "RETURN", "HALT",
  ]) {
    invariant(definition.instructions.some(({ name }) => name === requiredInstruction), `missing ${requiredInstruction} instruction`);
  }
}

function toPascalCase(value) {
  return value
    .toLowerCase()
    .split("_")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function generateJavaScript(definition) {
  const valueTypes = Object.fromEntries(definition.valueTypes.map(({ name, tag }) => [name, tag]));
  const opcodes = Object.fromEntries(definition.instructions.map(({ name, opcode }) => [name, opcode]));
  return `// Generated by tools/generate-isa.js from isa/v1.json. Do not edit.\n\n`
    + `export const FORMAT_VERSION = Object.freeze(${JSON.stringify(definition.formatVersion)});\n`
    + `export const BYTE_ORDER = ${JSON.stringify(definition.endianness)};\n`
    + `export const NO_REGISTER = ${definition.reservedValues.noRegister};\n`
    + `export const VALUE_TYPES = Object.freeze(${JSON.stringify(valueTypes, null, 2)});\n`
    + `export const OPCODES = Object.freeze(${JSON.stringify(opcodes, null, 2)});\n`
    + `export const OPERAND_TYPES = Object.freeze(${JSON.stringify(definition.operandTypes, null, 2)});\n`
    + `export const INSTRUCTIONS = Object.freeze(${JSON.stringify(definition.instructions, null, 2)});\n`;
}

function generateRust(definition) {
  const valueVariants = definition.valueTypes
    .map(({ name, tag }) => `    ${toPascalCase(name)} = ${tag},`)
    .join("\n");
  const valueMatches = definition.valueTypes
    .map(({ name, tag }) => `            ${tag} => Ok(Self::${toPascalCase(name)}),`)
    .join("\n");
  const opcodeVariants = definition.instructions
    .map(({ name, opcode }) => `    ${toPascalCase(name)} = ${opcode},`)
    .join("\n");
  const opcodeMatches = definition.instructions
    .map(({ name, opcode }) => `            ${opcode} => Ok(Self::${toPascalCase(name)}),`)
    .join("\n");
  const operandVariants = definition.operandTypes
    .map(({ name }) => `    ${toPascalCase(name)},`)
    .join("\n");
  const operandDefinitions = definition.operandTypes
    .map(({ name, encoding, allowsNoRegister }) => `    OperandTypeDefinition {
        name: "${name}",
        kind: OperandKind::${toPascalCase(name)},
        encoding: OperandEncoding::${encoding.toUpperCase()},
        allows_no_register: ${allowsNoRegister},
    },`)
    .join("\n");
  const instructionDefinitions = definition.instructions
    .map((instruction) => {
      const operands = instruction.operands
        .map(({ name, type }) => `            OperandDefinition {
                name: "${name}",
                kind: OperandKind::${toPascalCase(type)},
            },`)
        .join("\n");
      const encodedOperands = instruction.operands.length === 0
        ? "&[]"
        : instruction.operands.length === 1
          ? `&[OperandDefinition {
            name: "${instruction.operands[0].name}",
            kind: OperandKind::${toPascalCase(instruction.operands[0].type)},
        }]`
          : `&[\n${operands}\n        ]`;
      return `    InstructionDefinition {
        name: "${instruction.name}",
        opcode: Opcode::${toPascalCase(instruction.name)},
        operands: ${encodedOperands},
    },`;
    })
    .join("\n");

  return `// Generated by tools/generate-isa.js from isa/v1.json. Do not edit.\n`
    + `#![allow(dead_code)]\n\n`
    + `pub(crate) const FORMAT_MAJOR: u16 = ${definition.formatVersion.major};\n`
    + `pub(crate) const FORMAT_MINOR: u16 = ${definition.formatVersion.minor};\n`
    + `pub(crate) const NO_REGISTER: u16 = ${definition.reservedValues.noRegister};\n\n`
    + `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u8)]\npub(crate) enum ValueType {\n${valueVariants}\n}\n\n`
    + `impl TryFrom<u8> for ValueType {\n    type Error = ();\n\n    fn try_from(value: u8) -> Result<Self, Self::Error> {\n        match value {\n${valueMatches}\n            _ => Err(()),\n        }\n    }\n}\n\n`
    + `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u8)]\npub(crate) enum Opcode {\n${opcodeVariants}\n}\n\n`
    + `impl TryFrom<u8> for Opcode {\n    type Error = ();\n\n    fn try_from(value: u8) -> Result<Self, Self::Error> {\n        match value {\n${opcodeMatches}\n            _ => Err(()),\n        }\n    }\n}\n\n`
    + `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub(crate) enum OperandEncoding {\n    U16,\n    U32,\n}\n\n`
    + `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub(crate) enum OperandKind {\n${operandVariants}\n}\n\n`
    + `pub(crate) struct OperandTypeDefinition {\n    pub(crate) name: &'static str,\n    pub(crate) kind: OperandKind,\n    pub(crate) encoding: OperandEncoding,\n    pub(crate) allows_no_register: bool,\n}\n\n`
    + `pub(crate) struct OperandDefinition {\n    pub(crate) name: &'static str,\n    pub(crate) kind: OperandKind,\n}\n\n`
    + `pub(crate) struct InstructionDefinition {\n    pub(crate) name: &'static str,\n    pub(crate) opcode: Opcode,\n    pub(crate) operands: &'static [OperandDefinition],\n}\n\n`
    + `pub(crate) const OPERAND_TYPES: &[OperandTypeDefinition] = &[\n${operandDefinitions}\n];\n\n`
    + `pub(crate) const INSTRUCTIONS: &[InstructionDefinition] = &[\n${instructionDefinitions}\n];\n`;
}

function operandSummary(definition, instruction) {
  const types = new Map(definition.operandTypes.map((type) => [type.name, type]));
  if (instruction.operands.length === 0) return "—";
  return instruction.operands
    .map((operand) => {
      const type = types.get(operand.type);
      return `\`${operand.name}: ${operand.type} (${type.encoding})\``;
    })
    .join("<br>");
}

function generateDocumentation(definition, language) {
  const isEnglish = language === "en";
  const title = isEnglish
    ? "# JIMP Portable VM v1 — Generated ISA Reference"
    : "# VM Portátil JIMP v1 — Referência Gerada da ISA";
  const alternate = isEnglish
    ? "[Portuguese version](../PT/ISA.md)"
    : "[Versão em inglês](../EN/ISA.md)";
  const warning = isEnglish
    ? "This file is generated from [`isa/v1.json`](../../../isa/v1.json). Do not edit it manually."
    : "Este arquivo é gerado a partir de [`isa/v1.json`](../../../isa/v1.json). Não o edite manualmente.";
  const valueHeading = isEnglish ? "## Value type tags" : "## Tags dos tipos de valores";
  const instructionHeading = isEnglish ? "## Instructions" : "## Instruções";
  const valueHeader = isEnglish
    ? "| Tag | Name | Runtime value | Description |\n| ---: | --- | --- | --- |"
    : "| Tag | Nome | Valor de runtime | Descrição |\n| ---: | --- | --- | --- |";
  const instructionHeader = isEnglish
    ? "| Opcode | Name | Operands | Description |\n| ---: | --- | --- | --- |"
    : "| Opcode | Nome | Operandos | Descrição |\n| ---: | --- | --- | --- |";
  const yes = isEnglish ? "yes" : "sim";
  const no = isEnglish ? "no" : "não";
  const values = definition.valueTypes
    .map((type) => `| \`${type.tag}\` | \`${type.name}\` | ${type.runtimeValue ? yes : no} | ${type.description[language]} |`)
    .join("\n");
  const instructions = definition.instructions
    .map((instruction) => `| \`${instruction.opcode}\` | \`${instruction.name}\` | ${operandSummary(definition, instruction)} | ${instruction.description[language]} |`)
    .join("\n");

  return `${title}\n\n${alternate}\n\n> ${warning}\n\n`
    + `- ${isEnglish ? "Format version" : "Versão do formato"}: \`${definition.formatVersion.major}.${definition.formatVersion.minor}\`\n`
    + `- ${isEnglish ? "Byte order" : "Ordem dos bytes"}: \`${definition.endianness}-endian\`\n`
    + `- ${isEnglish ? "Opcode width" : "Tamanho do opcode"}: \`${definition.opcodeWidth} ${isEnglish ? "byte" : "byte"}\`\n`
    + `- \`NO_REGISTER\`: \`${definition.reservedValues.noRegister}\` (\`0xffff\`)\n\n`
    + `${valueHeading}\n\n${valueHeader}\n${values}\n\n`
    + `${instructionHeading}\n\n${instructionHeader}\n${instructions}\n`;
}

const definition = JSON.parse(readFileSync(definitionPath, "utf8"));
validateDefinition(definition);

const outputs = new Map([
  [resolve(repositoryRoot, "compiler/src/generated/isa.js"), generateJavaScript(definition)],
  [resolve(repositoryRoot, "runtime/src/generated/isa.rs"), generateRust(definition)],
  [resolve(repositoryRoot, "docs/specs/EN/ISA.md"), generateDocumentation(definition, "en")],
  [resolve(repositoryRoot, "docs/specs/PT/ISA.md"), generateDocumentation(definition, "pt")],
]);

const staleFiles = [];
for (const [outputPath, content] of outputs) {
  if (checkOnly) {
    if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== content) {
      staleFiles.push(relative(repositoryRoot, outputPath));
    }
    continue;
  }
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
}

if (staleFiles.length > 0) {
  throw new Error(`Generated ISA files are stale:\n${staleFiles.join("\n")}\nRun npm run generate:isa.`);
}

process.stdout.write(checkOnly ? "Generated ISA files are up to date.\n" : "Generated ISA files updated.\n");
