import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const definitionPath = resolve(repositoryRoot, "sandbox/v1.json");
const checkOnly = process.argv.slice(2).includes("--check");

function invariant(condition, message) {
  if (!condition) throw new Error(`Invalid sandbox definition: ${message}`);
}

function validateDefinition(definition) {
  invariant(definition.name === "jimp-reference-sandbox", "unexpected profile name");
  invariant(Number.isInteger(definition.version) && definition.version > 0, "invalid version");
  invariant(Array.isArray(definition.limits) && definition.limits.length > 0, "limits must be a non-empty array");
  const names = new Set();
  for (const limit of definition.limits) {
    invariant(/^[A-Z][A-Z0-9_]*$/.test(limit.name), `invalid limit name ${limit.name}`);
    invariant(!names.has(limit.name), `duplicate limit ${limit.name}`);
    names.add(limit.name);
    invariant(Number.isSafeInteger(limit.value) && limit.value > 0, `invalid value for ${limit.name}`);
    invariant(typeof limit.unit === "string" && limit.unit.length > 0, `missing unit for ${limit.name}`);
    invariant(["load", "verify", "execute"].includes(limit.phase), `invalid phase for ${limit.name}`);
    invariant(limit.description?.en && limit.description?.pt, `missing descriptions for ${limit.name}`);
  }
}

function generateJavaScript(definition) {
  const limits = Object.fromEntries(definition.limits.map(({ name, value }) => [name, value]));
  return `// Generated by tools/generate-sandbox.js from sandbox/v1.json. Do not edit.\n\n`
    + `export const SANDBOX_PROFILE = Object.freeze(${JSON.stringify({ name: definition.name, version: definition.version })});\n`
    + `export const SANDBOX_LIMITS = Object.freeze(${JSON.stringify(limits, null, 2)});\n`;
}

function generateRust(definition) {
  const constants = definition.limits
    .map(({ name, value }) => `pub(crate) const ${name}: usize = ${value};`)
    .join("\n");
  return `// Generated by tools/generate-sandbox.js from sandbox/v1.json. Do not edit.\n`
    + `#![allow(dead_code)]\n\n`
    + `pub(crate) const SANDBOX_PROFILE_NAME: &str = "${definition.name}";\n`
    + `pub(crate) const SANDBOX_PROFILE_VERSION: usize = ${definition.version};\n\n`
    + `${constants}\n`;
}

function generateDocumentation(definition, language) {
  const english = language === "en";
  const title = english ? "# JIMP Reference Sandbox v1" : "# Sandbox de Referência JIMP v1";
  const alternate = english ? "[Portuguese version](../PT/SANDBOX.md)" : "[Versão em inglês](../EN/SANDBOX.md)";
  const warning = english
    ? "This file is generated from [`sandbox/v1.json`](../../../sandbox/v1.json). Do not edit it manually."
    : "Este arquivo é gerado a partir de [`sandbox/v1.json`](../../../sandbox/v1.json). Não o edite manualmente.";
  const intro = english
    ? "These limits define the mandatory resource profile implemented by the official compiler tools and Rust runtime. Load and verification limits are checked before execution. Execution limits terminate the program with an error and do not roll back earlier authorized host effects. Runtime value memory is a portable logical charge, not a promise about process RSS or allocator overhead. The trust boundary, guarantees, and explicit non-guarantees are defined by the [sandbox and security model](SECURITY.md)."
    : "Estes limites definem o perfil obrigatório de recursos implementado pelas ferramentas oficiais do compilador e pelo runtime Rust. Limites de carregamento e verificação são checados antes da execução. Limites de execução encerram o programa com erro e não revertem efeitos autorizados anteriores no host. A memória de valores do runtime é uma cobrança lógica portátil, não uma garantia sobre RSS do processo ou overhead do alocador. A fronteira de confiança, as garantias e as não garantias explícitas são definidas pelo [modelo de sandbox e segurança](SECURITY.md).";
  const headings = english
    ? "| Phase | Limit | Value | Unit | Meaning |\n| --- | --- | ---: | --- | --- |"
    : "| Fase | Limite | Valor | Unidade | Significado |\n| --- | --- | ---: | --- | --- |";
  const phaseNames = english
    ? { load: "Load", verify: "Verify", execute: "Execute" }
    : { load: "Carregamento", verify: "Verificação", execute: "Execução" };
  const rows = definition.limits.map((limit) =>
    `| ${phaseNames[limit.phase]} | \`${limit.name}\` | ${limit.value.toLocaleString("en-US")} | ${limit.unit} | ${limit.description[language]} |`).join("\n");
  return `${title}\n\n${alternate}\n\n> ${warning}\n\n${intro}\n\n${headings}\n${rows}\n`;
}

const definition = JSON.parse(readFileSync(definitionPath, "utf8"));
validateDefinition(definition);

const outputs = new Map([
  [resolve(repositoryRoot, "compiler/src/generated/sandbox.js"), generateJavaScript(definition)],
  [resolve(repositoryRoot, "runtime/src/generated/sandbox.rs"), generateRust(definition)],
  [resolve(repositoryRoot, "docs/specs/EN/SANDBOX.md"), generateDocumentation(definition, "en")],
  [resolve(repositoryRoot, "docs/specs/PT/SANDBOX.md"), generateDocumentation(definition, "pt")],
]);

const staleFiles = [];
for (const [outputPath, content] of outputs) {
  if (checkOnly) {
    if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== content) {
      staleFiles.push(relative(repositoryRoot, outputPath));
    }
    continue;
  }
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
}

if (staleFiles.length > 0) {
  throw new Error(`Generated sandbox files are stale:\n${staleFiles.join("\n")}\nRun npm run generate:sandbox.`);
}

process.stdout.write(checkOnly ? "Generated sandbox files are up to date.\n" : "Generated sandbox files updated.\n");
