import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const definition = JSON.parse(readFileSync(resolve(repositoryRoot, "targets/v1.json"), "utf8"));
const standardLibrary = JSON.parse(readFileSync(resolve(repositoryRoot, "stdlib/v1.json"), "utf8"));
const checkOnly = process.argv.slice(2).includes("--check");

function invariant(condition, message) {
  if (!condition) throw new Error(`Invalid target profile definition: ${message}`);
}

function validateDefinition() {
  invariant(definition.name === "jimp-target-profiles" && definition.version === 1,
    "unsupported catalog identity");
  const optionalCapabilities = new Map();
  for (const module of standardLibrary.modules) {
    for (const exported of module.exports) {
      const symbol = exported.implementation?.optionalNative?.capability;
      if (symbol) optionalCapabilities.set(symbol, {
        parameterTypes: exported.parameters.map(({ type }) => type),
        returnType: exported.returnType,
      });
    }
  }
  const names = new Set();
  for (const profile of definition.profiles) {
    invariant(/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(profile.name),
      `invalid profile name ${profile.name}`);
    invariant(!names.has(profile.name), `duplicate profile ${profile.name}`);
    names.add(profile.name);
    invariant(profile.description?.en && profile.description?.pt,
      `missing description for ${profile.name}`);
    invariant(Array.isArray(profile.guaranteedCapabilities),
      `missing capabilities for ${profile.name}`);
    const symbols = new Set();
    for (const capability of profile.guaranteedCapabilities) {
      invariant(!symbols.has(capability.symbol),
        `duplicate capability ${capability.symbol} in ${profile.name}`);
      symbols.add(capability.symbol);
      const expected = optionalCapabilities.get(capability.symbol);
      invariant(expected, `unknown optional native capability ${capability.symbol}`);
      invariant(JSON.stringify(expected.parameterTypes) === JSON.stringify(capability.parameterTypes)
        && expected.returnType === capability.returnType,
      `incompatible signature for ${capability.symbol}`);
    }
    invariant([...symbols].join() === [...symbols].sort().join(),
      `capabilities for ${profile.name} must be sorted`);
  }
  invariant(names.has("portable"), "portable profile is required");
  invariant(definition.profiles.find(({ name }) => name === "portable").guaranteedCapabilities.length === 0,
    "portable profile cannot guarantee optional native capabilities");
}

function generateJavaScript() {
  return `// Generated by tools/generate-targets.js from targets/v1.json. Do not edit.\n\n`
    + `export const TARGET_PROFILES = Object.freeze(${JSON.stringify(definition.profiles, null, 2)});\n`;
}

function rustType(type) {
  return `ValueType::${type[0]}${type.slice(1).toLowerCase()}`;
}

function generateRust() {
  const capabilities = [];
  const profiles = definition.profiles.map((profile, profileIndex) => {
    const entries = profile.guaranteedCapabilities.map((capability, capabilityIndex) => {
      const parameterName = `PROFILE_${profileIndex}_CAPABILITY_${capabilityIndex}_PARAMETERS`;
      capabilities.push(`const ${parameterName}: &[ValueType] = &[${capability.parameterTypes.map(rustType).join(", ")}];`);
      return `    TargetCapability {\n`
        + `        symbol: "${capability.symbol}",\n`
        + `        parameter_types: ${parameterName},\n`
        + `        return_type: ${rustType(capability.returnType)},\n`
        + `    },`;
    });
    const arrayName = `PROFILE_${profileIndex}_CAPABILITIES`;
    capabilities.push(entries.length === 0
      ? `const ${arrayName}: &[TargetCapability] = &[];`
      : `const ${arrayName}: &[TargetCapability] = &[\n${entries.join("\n")}\n];`);
    return `    TargetProfile {\n`
      + `        name: "${profile.name}",\n`
      + `        guaranteed_capabilities: ${arrayName},\n`
      + `    },`;
  });
  return `// Generated by tools/generate-targets.js from targets/v1.json. Do not edit.\n\n`
    + `use crate::generated::isa::ValueType;\n\n`
    + `#[derive(Clone, Copy)]\npub(crate) struct TargetCapability {\n    pub(crate) symbol: &'static str,\n    pub(crate) parameter_types: &'static [ValueType],\n    pub(crate) return_type: ValueType,\n}\n\n`
    + `pub(crate) struct TargetProfile {\n    pub(crate) name: &'static str,\n    pub(crate) guaranteed_capabilities: &'static [TargetCapability],\n}\n\n`
    + `${capabilities.join("\n")}\n\n`
    + `pub(crate) const TARGET_PROFILES: &[TargetProfile] = &[\n${profiles.join("\n")}\n];\n`;
}

function generateDocumentation(language) {
  const english = language === "en";
  const title = english ? "# JIMP Target Profiles v1" : "# Perfis de Destino JIMP v1";
  const alternate = english ? "[Portuguese version](../PT/TARGETS.md)" : "[Versão em inglês](../EN/TARGETS.md)";
  const intro = english
    ? "Target profiles are explicit compiler/runtime contracts. Native standard-library replacement occurs only at link time; the runtime never probes or falls back dynamically."
    : "Perfis de destino são contratos explícitos entre compilador e runtime. A substituição nativa da biblioteca padrão ocorre somente na vinculação; o runtime nunca realiza sondagem nem fallback dinâmico.";
  const rows = definition.profiles.map((profile) => {
    const capabilities = profile.guaranteedCapabilities.map(({ symbol }) => `\`${symbol}\``).join(", ") || "—";
    return `| \`${profile.name}\` | ${capabilities} | ${profile.description[language]} |`;
  }).join("\n");
  const header = english
    ? "| Profile | Guaranteed optional capabilities | Contract |\n| --- | --- | --- |"
    : "| Perfil | Capacidades opcionais garantidas | Contrato |\n| --- | --- | --- |";
  return `${title}\n\n${alternate}\n\n> ${english ? "Generated from" : "Gerado de"} [\`targets/v1.json\`](../../../targets/v1.json).\n\n${intro}\n\n${header}\n${rows}\n`;
}

validateDefinition();
const outputs = new Map([
  [resolve(repositoryRoot, "compiler/src/generated/targets.js"), generateJavaScript()],
  [resolve(repositoryRoot, "runtime/src/generated/targets.rs"), generateRust()],
  [resolve(repositoryRoot, "docs/specs/EN/TARGETS.md"), generateDocumentation("en")],
  [resolve(repositoryRoot, "docs/specs/PT/TARGETS.md"), generateDocumentation("pt")],
]);
const stale = [];
for (const [path, content] of outputs) {
  if (checkOnly) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) stale.push(relative(repositoryRoot, path));
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}
if (stale.length > 0) throw new Error(`Generated target files are stale:\n${stale.join("\n")}`);
process.stdout.write(checkOnly ? "Generated target files are up to date.\n" : "Generated target files updated.\n");
