import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const definitionPath = resolve(repositoryRoot, "errors/v1.json");
const checkOnly = process.argv.slice(2).includes("--check");

function invariant(condition, message) {
  if (!condition) throw new Error(`Invalid error definition: ${message}`);
}

function validateDefinition(definition) {
  invariant(definition.name === "jimp-error", "unexpected error contract name");
  invariant(definition.version === 1, "unsupported error contract version");
  invariant(Array.isArray(definition.codes) && definition.codes.length > 0, "codes must be a non-empty array");
  const names = new Set();
  const codes = new Set();
  for (const error of definition.codes) {
    invariant(/^[A-Z][A-Z0-9_]*$/.test(error.name), `invalid name ${error.name}`);
    invariant(/^JIMP-[0-9]{4}$/.test(error.code), `invalid code ${error.code}`);
    invariant(!names.has(error.name), `duplicate name ${error.name}`);
    invariant(!codes.has(error.code), `duplicate code ${error.code}`);
    names.add(error.name);
    codes.add(error.code);
    invariant(["usage", "io", "compile", "decode", "verify", "resolve", "execute", "internal"].includes(error.phase), `invalid phase for ${error.name}`);
    invariant(Number.isInteger(error.exitCode) && error.exitCode >= 1 && error.exitCode <= 255, `invalid exit code for ${error.name}`);
    invariant(error.description?.en && error.description?.pt, `missing descriptions for ${error.name}`);
  }
}

function generateJavaScript(definition) {
  const entries = definition.codes.map((error) =>
    `  ${error.name}: Object.freeze(${JSON.stringify({ code: error.code, phase: error.phase, exitCode: error.exitCode })}),`).join("\n");
  return `// Generated by tools/generate-errors.js from errors/v1.json. Do not edit.\n\n`
    + `export const ERROR_SCHEMA = ${JSON.stringify(`${definition.name}-v${definition.version}`)};\n`
    + `export const ERROR_CODES = Object.freeze({\n${entries}\n});\n`;
}

function generateRust(definition) {
  const constants = definition.codes.map((error) =>
    `pub(crate) const ${error.name}: ErrorDefinition = ErrorDefinition {\n`
    + `    code: "${error.code}",\n`
    + `    phase: "${error.phase}",\n`
    + `    exit_code: ${error.exitCode},\n`
    + `};`).join("\n");
  return `// Generated by tools/generate-errors.js from errors/v1.json. Do not edit.\n`
    + `#![allow(dead_code)]\n\n`
    + `pub(crate) const ERROR_SCHEMA: &str = "${definition.name}-v${definition.version}";\n\n`
    + `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n`
    + `pub(crate) struct ErrorDefinition {\n`
    + `    pub(crate) code: &'static str,\n`
    + `    pub(crate) phase: &'static str,\n`
    + `    pub(crate) exit_code: i32,\n`
    + `}\n\n${constants}\n`;
}

function generateDocumentation(definition, language) {
  const english = language === "en";
  const title = english ? "# JIMP Standard Error Format v1" : "# Formato Padrão de Erros JIMP v1";
  const alternate = english ? "[Portuguese version](../PT/ERRORS.md)" : "[Versão em inglês](../EN/ERRORS.md)";
  const warning = english
    ? "This file is generated from [`errors/v1.json`](../../../errors/v1.json). Do not edit it manually."
    : "Este arquivo é gerado a partir de [`errors/v1.json`](../../../errors/v1.json). Não o edite manualmente.";
  const intro = english
    ? "Compiler tools and runtimes report failures using a stable code, phase, message, and optional location. Human-readable output is the default. Passing `--error-format=json` emits one JSON object to standard error. Diagnostic text is not a compatibility boundary; `schema`, `code`, and `phase` are."
    : "As ferramentas do compilador e os runtimes relatam falhas usando código, fase, mensagem e localização opcional. A saída legível é o padrão. A opção `--error-format=json` emite um objeto JSON em uma linha na saída de erro. O texto do diagnóstico não é uma fronteira de compatibilidade; `schema`, `code` e `phase` são.";
  const human = english
    ? "`JIMP error JIMP-1001 (compile) at source line 3: Undefined identifier value.`"
    : "`JIMP error JIMP-1001 (compile) at source line 3: Identificador value não definido.`";
  const locationText = english
    ? "`location` is omitted when unavailable. Source locations use `{\"kind\":\"source\",\"line\":N}`. Bytecode locations use `{\"kind\":\"bytecode\",\"offset\":N}`. Line numbers are one-based; byte offsets are zero-based. Runtime source locations are populated from the optional `.jbc` debug section."
    : "`location` é omitido quando indisponível. Localizações de fonte usam `{\"kind\":\"source\",\"line\":N}`. Localizações de bytecode usam `{\"kind\":\"bytecode\",\"offset\":N}`. Linhas começam em um; offsets de bytecode começam em zero. Localizações de fonte do runtime são preenchidas pela seção opcional de debug do `.jbc`.";
  const tableHeader = english
    ? "| Code | Phase | CLI exit | Meaning |\n| --- | --- | ---: | --- |"
    : "| Código | Fase | Saída CLI | Significado |\n| --- | --- | ---: | --- |";
  const rows = definition.codes.map((error) =>
    `| \`${error.code}\` | \`${error.phase}\` | ${error.exitCode} | ${error.description[language]} |`).join("\n");
  const headings = english
    ? { contract: "## Contract", human: "## Human output", json: "## JSON output", locations: "## Locations", codes: "## Codes" }
    : { contract: "## Contrato", human: "## Saída legível", json: "## Saída JSON", locations: "## Localizações", codes: "## Códigos" };
  const contractText = english
    ? "`schema`, `code`, `phase`, and `message` are required. `location` is optional. Consumers must ignore unknown fields so compatible metadata can be added later."
    : "`schema`, `code`, `phase` e `message` são obrigatórios. `location` é opcional. Consumidores devem ignorar campos desconhecidos para permitir a adição posterior de metadados compatíveis.";
  const contract = english
    ? `{"schema":"jimp-error-v1","code":"JIMP-1001","phase":"compile","message":"Undefined identifier value.","location":{"kind":"source","line":3}}`
    : `{"schema":"jimp-error-v1","code":"JIMP-1001","phase":"compile","message":"Identificador value não definido.","location":{"kind":"source","line":3}}`;
  return `${title}\n\n${alternate}\n\n> ${warning}\n\n${intro}\n\n${headings.contract}\n\n${contractText}\n\n${headings.human}\n\n${human}\n\n${headings.json}\n\n\`\`\`json\n${contract}\n\`\`\`\n\n${headings.locations}\n\n${locationText}\n\n${headings.codes}\n\n${tableHeader}\n${rows}\n`;
}

const definition = JSON.parse(readFileSync(definitionPath, "utf8"));
validateDefinition(definition);

const outputs = new Map([
  [resolve(repositoryRoot, "compiler/src/generated/errors.js"), generateJavaScript(definition)],
  [resolve(repositoryRoot, "runtime/src/generated/errors.rs"), generateRust(definition)],
  [resolve(repositoryRoot, "docs/specs/EN/ERRORS.md"), generateDocumentation(definition, "en")],
  [resolve(repositoryRoot, "docs/specs/PT/ERRORS.md"), generateDocumentation(definition, "pt")],
]);

const staleFiles = [];
for (const [outputPath, content] of outputs) {
  if (checkOnly) {
    if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== content) {
      staleFiles.push(relative(repositoryRoot, outputPath));
    }
    continue;
  }
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
}

if (staleFiles.length > 0) {
  throw new Error(`Generated error files are stale:\n${staleFiles.join("\n")}\nRun npm run generate:errors.`);
}

process.stdout.write(checkOnly ? "Generated error files are up to date.\n" : "Generated error files updated.\n");
